name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install
        run: pnpm install
        
      - name: Fix
        run: pnpm run lint:fix
        
      - name: Lint
        run: pnpm run lint
